service:
  name: Microsoft 365
  category: productivity
  status: sanctioned
  risk_level: low
network:
  domains:
  - microsoft-365.com
  - '*.microsoft-365.com'
  - api.microsoft-365.com
  - app.microsoft-365.com
  - cdn.microsoft-365.com
  - static.microsoft-365.com
  - microsoft-365.io
  ip_ranges:
  - 52.209.0.0/16
  - 172.20.0.0/16
traffic_patterns:
  web_paths:
  - /dashboard
  - /
  - /projects
  - /tasks
  - /login
  - /calendar
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
  api_endpoints:
  - /api/v1/auth
  - /api/v1/users
  - /api/v1/data
  - /api/v1/productivity
activity:
  user_adoption_rate: 0.68
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
    document_edit:
      weight: 0.3
      avg_duration_seconds: 300
    task_create:
      weight: 0.1
      avg_per_hour: 5
    task_update:
      weight: 0.1
      avg_per_hour: 10
security_events:
  block_rate: 0.001
traffic_override:
  access_count_per_hour:
    normal:
      mean: 25  # Normal users access Office 365 ~25 times per hour during work
      std: 5
    power_user:
      mean: 40  # Power users access more frequently
      std: 10
    risky:
      mean: 20  # Risky users might use it less
      std: 8
  bandwidth_per_user:
    normal:
      daily_mb: 500  # ~500MB per day for normal users
      peak_multiplier: 2.5
    power_user:
      daily_mb: 1500  # Power users use more bandwidth
      peak_multiplier: 3.0
    risky:
      daily_mb: 300
      peak_multiplier: 2.0
