service:
  name: OneDrive
  category: cloud_storage
  status: sanctioned
  risk_level: low
network:
  domains:
  - onedrive.com
  - '*.onedrive.com'
  - cdn.onedrive.com
  - static.onedrive.com
  - files.onedrive.com
  - download.onedrive.com
  ip_ranges:
  - 104.190.0.0/16
  - 52.26.0.0/16
  - 104.215.0.0/16
traffic_patterns:
  web_paths:
  - /files
  - /dashboard
  - /login
  - /api/v2
  - /upload
  - /download
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
activity:
  user_adoption_rate: 0.8
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
    file_upload:
      weight: 0.2
      avg_size_mb: 10
      size_std_dev: 5
    file_download:
      weight: 0.2
      avg_size_mb: 8
      size_std_dev: 4
    folder_browse:
      weight: 0.1
      avg_duration_seconds: 20
security_events:
  block_rate: 0.001
traffic_override:
  access_count_per_hour:
    normal:
      mean: 15  # Normal users sync/access files ~15 times per hour
      std: 5
    power_user:
      mean: 30  # Power users work with files more frequently
      std: 10
    risky:
      mean: 10
      std: 5
  bandwidth_per_user:
    normal:
      daily_mb: 1000  # ~1GB per day for file syncing
      peak_multiplier: 4.0  # Large file uploads/downloads spike bandwidth
    power_user:
      daily_mb: 3000  # Power users sync more files
      peak_multiplier: 5.0
    risky:
      daily_mb: 500
      peak_multiplier: 3.0
